apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  annotations: arn:aws:iam::471112727668:role/eks-iam-role-dummy
---
apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  containers:
    - name: test
      image: amazon/aws-cli
      command: [ "tail","-f" , "/dev/null" ]