apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummy
  annotations: arn:aws:iam::471112727668:role/eks-iam-role-dummy
---
apiVersion: v1
kind: Pod
metadata:
  name: dummy
  labels:
    app: dummy
spec:
  containers:
    - name: dummy
      image: amazon/aws-cli
      command: [ "tail","-f" , "/dev/null" ]