apiVersion: v1
kind: pod
metadata:
  name: storage-demo
spec:
  initContainers:
    - name: con1
      image: centos
      command: [ "tail" , "-f" ,"/dev/null" ]
  volumeMounts:
    - mountPath: /parameters
      name: cache-volume
  containers:
    - name: con2
      image: centos
      command: [ "tail" , "-f" ,"/dev/null" ]
  volumeMounts:
    - mountPath: /parameters
      name: cache-volume
  volumes:
    - name: parameters
      emptyDir:
        sizeLimit: 5Mi