apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}
  labels:
    app: {{.Values.appName}}
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::471112727668:role/prod-expense-{{ .Values.appName }}-eks-sa
spec:
  type: LoadBalancer
  selector:
    app: {{.Values.appName}}
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}