apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: 471112727668.dkr.ecr.us-east-1.amazonaws.com/frontend:2.0.5
  imagePullSecrets:
    - name: aws-ecr

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: backend
      image: 471112727668.dkr.ecr.us-east-1.amazonaws.com/backend:3.0.0
    imagePullSecrets:
      - name: aws-ecr