apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: 471112727668.dkr.ecr.us-east-1.amazonaws.com/frontend:5.0.2
  imagePullSecrets:
    - name: aws-ecr

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations: arn:aws:iam::471112727668:role/prod-expense-frontend-eks-sa
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: 471112727668.dkr.ecr.us-east-1.amazonaws.com/backend:3.0.0
      env:
        - name: DB_HOST
          value: aurora-cluster-dev.cluster-cjmks6wgq3k7.us-east-1.rds.amazonaws.com
        - name: DB_PWD
          value: "expenseprod1234"
        - name: DB_USER
          value: expenseprod
  imagePullSecrets:
    - name: aws-ecr

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations: arn:aws:iam::471112727668:role/prod-expense-backend-eks-sa
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: batch/v1
kind: Job
metadata:
  name: schema
  annotations: arn:aws:iam::471112727668:role/prod-expense-schema-eks-sa
spec:
  template:
    spec:
      imagePullSecrets:
        - name: aws-ecr
      restartPolicy: Never
      containers:
        - name: schema
          image: 471112727668.dkr.ecr.us-east-1.amazonaws.com/expense-load-schema:3.0.3
          env:
            - name: DB_HOST
              value: aurora-cluster-dev.cluster-cjmks6wgq3k7.us-east-1.rds.amazonaws.com
            - name: DB_PASS
              value: "expenseprod1234"
            - name: DB_USER
              value: expenseprod
            - name: COMPONENT
              value: backend