apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: 471112727668.dkr.ecr.us-east-1.amazonaws.com/frontend:5.0.0
  imagePullSecrets:
    - name: aws-ecr

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: 471112727668.dkr.ecr.us-east-1.amazonaws.com/backend:3.0.0
  imagePullSecrets:
    - name: aws-ecr
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: batch/v1
kind: Job
metadata:
  name: schema
spec:
  template:
    spec:
      containers:
        - name: schema
          image:
          command: [ "perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)" ]
      restartPolicy: Never
  backoffLimit: 4